

<h2>Створити новину</h2>

<form name="createNews"  method="POST">
    <label for="code">Code</label>
    <input minlength="1" id="code" name="code" type="text"><br />

    <label for="title">title</label>
    <input minlength="3" id="title" name="title" type="text"><br />

    <label for="description">description</label>
    <input minlength="5" id="description" name="description" type="text"><br />

    <label for="text">text</label>
    <input minlength="10" id="text" name="text" type="text"><br />

    <button name="createNews" type="submit">Add</button>
</form>